services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        fromDatabase:
          name: portfolio-db
          property: secret_key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-render-app-url.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
    healthCheckPath: /admin/
    autoDeploy: true

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free 